#!/system/bin/sh

# Disable mpdecision, thermald & logcat
 	stop thermald
 	stop mpdecision
	stop logd

# Set hotplug values
	echo "87" > /sys/devices/virtual/misc/mako_hotplug/load_threshold
	echo "17" > /sys/devices/virtual/misc/mako_hotplug/high_load_counter
	echo "12" > /sys/devices/virtual/misc/mako_hotplug/max_load_counter
	echo "1300000" > /sys/devices/virtual/misc/mako_hotplug/cpufreq_unplug_limit
	echo "1" > /sys/devices/virtual/misc/mako_hotplug/min_time_cpu_online
	echo "2" > /sys/devices/virtual/misc/mako_hotplug/timer

# Set GPU values
	echo "30" > /sys/module/msm_kgsl_core/parameters/down_threshold
	echo "55" > /sys/module/msm_kgsl_core/parameters/up_threshold

# Set Governor values
	echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo "interactive" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
	echo "interactive" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
	echo "interactive" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor

	echo "1134000" > /sys/devices/system/cpu/cpufreq/interactive/input_boost_freq
	echo "92" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
	echo "918000" > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
	echo "200000" > /sys/devices/system/cpu/cpufreq/interactive/boostpulse_duration
