#!/system/bin/sh

# Disable mpdecision & thermald (if existing in rom)
 	stop thermald
 	stop mpdecision

# Set Gorvernor interactive or ondemand
	GOV=interactive
	echo $GOV > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo $GOV > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
	echo $GOV > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
	echo $GOV > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor

# Set hotplug values
	echo 90 > /sys/class/misc/mako_hotplug_control/load_threshold
	echo 20 > /sys/class/misc/mako_hotplug_control/high_load_counter
	echo 10 > /sys/class/misc/mako_hotplug_control/max_load_counter
	echo 1350000 > /sys/class/misc/mako_hotplug_control/cpufreq_unplug_limit
	echo 1 > /sys/class/misc/mako_hotplug_control/min_time_cpu_online
	echo 2 > /sys/class/misc/mako_hotplug_control/timer

# Set GPU values
# not yet implemented
	#echo "30" > /sys/module/msm_kgsl_core/parameters/down_threshold
	#echo "55" > /sys/module/msm_kgsl_core/parameters/up_threshold
